"""
Me'morAI — QMQ/ShNQ 50+ qoidalarni to'liq generatsiya qilish skripti.
O'zbekiston Respublikasi Qurilish Vazirligi (mc.uz) rasmiy me'yorlari asosida.
"""
import json
from pathlib import Path

RULES = [
    # ─── 1. YONG'IN XAVFSIZLIGI (ShNQ 2.01.02-04) ───
    {
        "id": "UZ-FIRE-001",
        "code": "ShNQ 2.01.02-04",
        "clause": "Ilova 1, §3.10",
        "category": "yong_in_xavfsizligi",
        "severity": "critical",
        "title_uz": "Yong'in o'chirish texnikasi o'tish yo'li kengligi",
        "title_ru": "Ширина проезда для пожарных машин",
        "description_uz": "Yong'in o'chirish avtomashinalari uchun o'tish yo'lining kengligi kamida 6 metr bo'lishi shart.",
        "description_ru": "Ширина проезда для пожарных машин должна быть не менее 6 м.",
        "check_type": "min_value",
        "metric": "fire_access_road_width_m",
        "unit": "m",
        "min_value": 6.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Yong'in o'tish yo'li kengligi {actual}m — me'yor bo'yicha kamida {required}m bo'lishi shart (ShNQ 2.01.02-04, §3.10)",
        "error_template_ru": "Ширина проезда {actual}м — по норме не менее {required}м (ШНК 2.01.02-04, §3.10)"
    },
    {
        "id": "UZ-FIRE-002",
        "code": "ShNQ 2.01.02-04",
        "clause": "Ilova 1, §3.12",
        "category": "yong_in_xavfsizligi",
        "severity": "critical",
        "title_uz": "Yong'in o'tish tunneli minimal o'lchamlari",
        "title_ru": "Минимальные размеры пожарного тоннеля",
        "description_uz": "Har 100 metr fasad bo'ylab yong'in tushish o'tish yo'llari: balandligi kamida 4.25m, kengligi kamida 3.5m.",
        "description_ru": "Через каждые 100 м по фасаду — проезды (тоннели): высота не менее 4,25 м, ширина не менее 3,5 м.",
        "check_type": "min_value",
        "metric": "fire_tunnel_height_m",
        "unit": "m",
        "min_value": 4.25,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Yong'in tunneli balandligi {actual}m (kamida {required}m talab etiladi) — ShNQ 2.01.02-04 §3.12",
        "error_template_ru": "Высота пожарного тоннеля {actual}м (требуется ≥{required}м) — ШНК 2.01.02-04 §3.12"
    },
    {
        "id": "UZ-FIRE-003",
        "code": "ShNQ 2.01.02-04",
        "clause": "Ilova 1, §3.13",
        "category": "yong_in_xavfsizligi",
        "severity": "high",
        "title_uz": "Bino devoridan o'tish yo'li chekkasigacha masofa",
        "title_ru": "Расстояние от стены здания до края проезда",
        "description_uz": "Bino devoridan o'tish yo'li chekkasigacha: balandligi 10 qavatgacha binolar uchun 5-8m.",
        "description_ru": "Расстояние от стены здания до края проезда: для зданий до 10 этажей — 5-8 м.",
        "check_type": "range",
        "metric": "fire_road_to_wall_distance_m",
        "unit": "m",
        "min_value": 5.0,
        "max_value": 8.0,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Bino devoridan masofa {actual}m — me'yor: 5.0m dan 8.0m gacha (ShNQ 2.01.02-04 §3.13)",
        "error_template_ru": "Расстояние от стены {actual}м — по норме: от 5.0м до 8.0м (ШНК 2.01.02-04 §3.13)"
    },
    {
        "id": "UZ-FIRE-004",
        "code": "ShNQ 2.01.02-04",
        "clause": "§4.15",
        "category": "yong_in_xavfsizligi",
        "severity": "critical",
        "title_uz": "Evakuatsiya zinalari toza marsh kengligi",
        "title_ru": "Ширина марша эвакуационной лестницы",
        "description_uz": "Ko'p kvartirali turar-joy va jamoat binolarida evakuatsiya zinalari marshi kengligi kamida 1.20 metr.",
        "description_ru": "Ширина лестничного марша должна быть не менее 1.20 м.",
        "check_type": "min_value",
        "metric": "evacuation_stair_width_m",
        "unit": "m",
        "min_value": 1.20,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Zina marshi kengligi {actual}m — kamida {required}m bo'lishi shart (ShNQ 2.01.02-04 §4.15)",
        "error_template_ru": "Ширина лестничного марша {actual}м — не менее {required}м (ШНК 2.01.02-04 §4.15)"
    },
    {
        "id": "UZ-FIRE-005",
        "code": "ShNQ 2.01.02-04",
        "clause": "§4.22",
        "category": "yong_in_xavfsizligi",
        "severity": "critical",
        "title_uz": "Evakuatsiya yo'lagi (tupik) maksimal uzunligi",
        "title_ru": "Предельная длина тупикового коридора",
        "description_uz": "Xonadon eshigidan tutun chiqmaydigan zina katagigacha bo'lgan tupik yo'lak uzunligi 25 metrdan oshmasligi kerak.",
        "description_ru": "Длина тупикового коридора не должна превышать 25 м.",
        "check_type": "max_value",
        "metric": "dead_end_corridor_length_m",
        "unit": "m",
        "max_value": 25.0,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Tupik yo'lak uzunligi {actual}m — ruxsat etilgan maksimal me'yor {required}m (ShNQ 2.01.02-04 §4.22)",
        "error_template_ru": "Длина тупикового коридора {actual}м — максимум {required}м (ШНК 2.01.02-04 §4.22)"
    },
    {
        "id": "UZ-FIRE-006",
        "code": "ShNQ 2.01.02-04",
        "clause": "§4.28",
        "category": "yong_in_xavfsizligi",
        "severity": "high",
        "title_uz": "Umumiy evakuatsiya yo'lagi kengligi",
        "title_ru": "Ширина эвакуационного коридора",
        "description_uz": "Odamlar oqimi 50 dan ortiq bo'lgan umumiy foydalanish koridorlari kengligi kamida 1.40m bo'lishi shart.",
        "description_ru": "Ширина эвакуационного коридора должна быть не менее 1.40 м.",
        "check_type": "min_value",
        "metric": "evacuation_corridor_width_m",
        "unit": "m",
        "min_value": 1.40,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Evakuatsiya koridori kengligi {actual}m — kamida {required}m bo'lishi shart (ShNQ 2.01.02-04 §4.28)",
        "error_template_ru": "Ширина коридора {actual}м — не менее {required}м (ШНК 2.01.02-04 §4.28)"
    },
    {
        "id": "UZ-FIRE-007",
        "code": "ShNQ 2.01.02-04",
        "clause": "§5.10",
        "category": "yong_in_xavfsizligi",
        "severity": "critical",
        "title_uz": "Baland binolarda tutun chiqmaydigan zina katagi turi",
        "title_ru": "Незадымляемые лестничные клетки (Н1)",
        "description_uz": "Balandligi 28 metrdan (taxminan 9 qavat) oshgan binolarda H1 turidagi tashqi havo orqali o'tiladigan tutunsiz zina kataklari talab qilinadi.",
        "description_ru": "При высоте здания более 28 м требуются незадымляемые клетки типа Н1.",
        "check_type": "min_value",
        "metric": "building_height_fire_limit_m",
        "unit": "m",
        "min_value": 28.0,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Bino balandligi {actual}m ≥ 28m: H1 tutunsiz zina katagi va havo bosimi tizimi majburiy!",
        "error_template_ru": "Высота здания {actual}м ≥ 28м: требуется незадымляемая лестничная клетка Н1!"
    },
    {
        "id": "UZ-FIRE-008",
        "code": "ShNQ 2.01.02-04",
        "clause": "§6.04",
        "category": "yong_in_xavfsizligi",
        "severity": "high",
        "title_uz": "Yong'in gidranti maksimal masofasi",
        "title_ru": "Расстояние до пожарного гидранта",
        "description_uz": "Tashqi yong'in gidrantigacha bo'lgan masofa avtomobil yo'li bo'ylab 100 metrdan oshmasligi kerak.",
        "description_ru": "Расстояние до пожарного гидранта не более 100 м.",
        "check_type": "max_value",
        "metric": "fire_hydrant_distance_m",
        "unit": "m",
        "max_value": 100.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Yong'in gidrantigacha masofa {actual}m — me'yordan oshiq (max {required}m, ShNQ 2.01.02-04 §6.04)",
        "error_template_ru": "Расстояние до гидранта {actual}м — превышает норму {required}м (ШНК 2.01.02-04 §6.04)"
    },
    {
        "id": "UZ-FIRE-009",
        "code": "ShNQ 2.01.02-04",
        "clause": "§2.12",
        "category": "yong_in_xavfsizligi",
        "severity": "critical",
        "title_uz": "Yong'inga qarshi 1-turdagi devor (Brandmauer) chegarasi",
        "title_ru": "Огнестойкость противопожарных стен 1-го типа",
        "description_uz": "1-turdagi yong'inga qarshi devorlar kamida REI 150 (2.5 soat) yong'inga chidamlilik chegarasiga ega bo'lishi shart.",
        "description_ru": "Предел огнестойкости противопожарных стен 1-го типа не менее REI 150.",
        "check_type": "min_value",
        "metric": "fire_wall_rei_minutes",
        "unit": "min",
        "min_value": 150.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Devorning yong'inga chidamliligi REI {actual} — me'yor bo'yicha kamida REI {required} talab etiladi",
        "error_template_ru": "Предел огнестойкости стены REI {actual} — требуется не менее REI {required}"
    },
    {
        "id": "UZ-FIRE-010",
        "code": "ShNQ 2.01.02-04",
        "clause": "§7.01",
        "category": "yong_in_xavfsizligi",
        "severity": "high",
        "title_uz": "Evakuatsiya chiqish eshiklari toza kengligi",
        "title_ru": "Ширина эвакуационных дверей",
        "description_uz": "Binodan tashqariga yoki zina katagiga chiqish eshigining toza kengligi kamida 0.90m bo'lishi shart.",
        "description_ru": "Ширина эвакуационных выходов не менее 0.90 м.",
        "check_type": "min_value",
        "metric": "evacuation_door_width_m",
        "unit": "m",
        "min_value": 0.90,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Evakuatsiya eshigi toza kengligi {actual}m — kamida {required}m talab etiladi (ShNQ 2.01.02-04 §7.01)",
        "error_template_ru": "Ширина двери {actual}м — требуется не менее {required}м (ШНК 2.01.02-04 §7.01)"
    },

    # ─── 2. NOGIRONLAR VA QULAY MUHIT (ShNQ 2.07.02-22) ───
    {
        "id": "UZ-ACC-001",
        "code": "ShNQ 2.07.02-22",
        "clause": "§17",
        "category": "nogironlar_muhiti",
        "severity": "critical",
        "title_uz": "Pandus maksimal qiyaligi (yangi qurilish)",
        "title_ru": "Предельный уклон пандуса (новое строительство)",
        "description_uz": "Yangi qurilishda pandusning bo'ylama qiyaligi 1:12 (8.33%) dan oshmasligi shart.",
        "description_ru": "Уклон пандуса при новом строительстве не должен превышать 1:12 (8.33%).",
        "check_type": "max_value",
        "metric": "ramp_slope_percent",
        "unit": "%",
        "max_value": 8.33,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Pandus qiyaligi {actual}% — maksimal me'yor {required}% (ShNQ 2.07.02-22, §17)",
        "error_template_ru": "Уклон пандуса {actual}% — максимум {required}% (ШНК 2.07.02-22, §17)"
    },
    {
        "id": "UZ-ACC-002",
        "code": "ShNQ 2.07.02-22",
        "clause": "§18",
        "category": "nogironlar_muhiti",
        "severity": "critical",
        "title_uz": "Pandus minimal kengligi",
        "title_ru": "Минимальная ширина пандуса",
        "description_uz": "Pandusning toza o'tish kengligi kamida 1.20 metr (bir tomonlama) bo'lishi shart.",
        "description_ru": "Ширина пандуса в чистоте должна быть не менее 1.20 м.",
        "check_type": "min_value",
        "metric": "ramp_width_m",
        "unit": "m",
        "min_value": 1.20,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Pandus kengligi {actual}m — kamida {required}m talab etiladi (ShNQ 2.07.02-22 §18)",
        "error_template_ru": "Ширина пандуса {actual}м — требуется не менее {required}м (ШНК 2.07.02-22 §18)"
    },
    {
        "id": "UZ-ACC-003",
        "code": "ShNQ 2.07.02-22",
        "clause": "§19",
        "category": "nogironlar_muhiti",
        "severity": "high",
        "title_uz": "Pandus burilish maydonchasi o'lchami",
        "title_ru": "Размер поворотной площадки пандуса",
        "description_uz": "Pandus yo'nalishi o'zgarganda oraliq gorizontal maydoncha kamida 1.50x1.50m bo'lishi lozim.",
        "description_ru": "Размер поворотной площадки пандуса не менее 1.50х1.50 м.",
        "check_type": "min_value",
        "metric": "ramp_landing_dimension_m",
        "unit": "m",
        "min_value": 1.50,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Pandus burilish maydonchasi {actual}m — kamida {required}m bo'lishi kerak (ShNQ 2.07.02-22 §19)",
        "error_template_ru": "Площадка пандуса {actual}м — не менее {required}м (ШНК 2.07.02-22 §19)"
    },
    {
        "id": "UZ-ACC-004",
        "code": "ShNQ 2.07.02-22",
        "clause": "§22",
        "category": "nogironlar_muhiti",
        "severity": "high",
        "title_uz": "Kirish eshigi toza o'tish kengligi",
        "title_ru": "Ширина входных дверей для МГН",
        "description_uz": "Nogironligi bo'lgan shaxslar harakatlanadigan asosiy kirish eshigi toza kengligi kamida 0.90m.",
        "description_ru": "Ширина входных дверей не менее 0.90 м.",
        "check_type": "min_value",
        "metric": "entrance_door_clear_width_m",
        "unit": "m",
        "min_value": 0.90,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Kirish eshigi toza kengligi {actual}m — kamida {required}m bo'lishi shart (ShNQ 2.07.02-22 §22)",
        "error_template_ru": "Ширина входной двери {actual}м — не менее {required}м (ШНК 2.07.02-22 §22)"
    },
    {
        "id": "UZ-ACC-005",
        "code": "ShNQ 2.07.02-22",
        "clause": "§25",
        "category": "nogironlar_muhiti",
        "severity": "medium",
        "title_uz": "Eshik ostonasi (porog) maksimal balandligi",
        "title_ru": "Высота дверного порога",
        "description_uz": "Ostonalar balandligi 0.014m (14mm) dan oshmasligi, qirralari qiya qilinishi kerak.",
        "description_ru": "Высота дверного порога не должна превышать 0.014 м (14 мм).",
        "check_type": "max_value",
        "metric": "door_threshold_height_m",
        "unit": "m",
        "max_value": 0.014,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Eshik ostonasi {actual}m — ruxsat etilgan maksimal me'yor {required}m (14mm) (ShNQ 2.07.02-22 §25)",
        "error_template_ru": "Высота порога {actual}м — превышает норму {required}м (ШНК 2.07.02-22 §25)"
    },
    {
        "id": "UZ-ACC-006",
        "code": "ShNQ 2.07.02-22",
        "clause": "§28",
        "category": "nogironlar_muhiti",
        "severity": "high",
        "title_uz": "Aravacha burilish doirasi diametri",
        "title_ru": "Зона разворота кресла-коляски",
        "description_uz": "Koridorlar va xonalarda aravachaning 360 daraja erkin burilish doirasi kamida 1.50m diametrda bo'lishi shart.",
        "description_ru": "Диаметр зоны разворота кресла-коляски не менее 1.50 м.",
        "check_type": "min_value",
        "metric": "wheelchair_turning_diameter_m",
        "unit": "m",
        "min_value": 1.50,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Aravacha burilish doirasi {actual}m — kamida {required}m talab etiladi (ShNQ 2.07.02-22 §28)",
        "error_template_ru": "Зона разворота {actual}м — не менее {required}м (ШНК 2.07.02-22 §28)"
    },
    {
        "id": "UZ-ACC-007",
        "code": "ShNQ 2.07.02-22",
        "clause": "§34",
        "category": "nogironlar_muhiti",
        "severity": "critical",
        "title_uz": "Nogironlar sanitariya tuguni minimal o'lchami",
        "title_ru": "Размеры санузла для МГН",
        "description_uz": "Universal kabina o'lchami rejadagi tozalikda kamida 1.65x1.80m bo'lishi shart.",
        "description_ru": "Размеры универсальной кабины не менее 1.65х1.80 м.",
        "check_type": "min_value",
        "metric": "accessible_toilet_width_m",
        "unit": "m",
        "min_value": 1.65,
        "applies_to": ["commercial", "public", "residential"],
        "error_template_uz": "Maxsus hojatxona eni {actual}m — me'yor bo'yicha kamida {required}m bo'lishi shart (ShNQ 2.07.02-22 §34)",
        "error_template_ru": "Ширина санузла {actual}м — не менее {required}м (ШНК 2.07.02-22 §34)"
    },
    {
        "id": "UZ-ACC-008",
        "code": "ShNQ 2.07.02-22",
        "clause": "§40",
        "category": "nogironlar_muhiti",
        "severity": "high",
        "title_uz": "Nogironlar lift kabinasi ichki o'lchami",
        "title_ru": "Габариты кабины лифта для МГН",
        "description_uz": "Aravachali shaxslar uchun mo'ljallangan lift kabinasi o'lchami kamida 1.10m (eni) va 1.40m (chuqurligi).",
        "description_ru": "Габариты кабины лифта не менее 1.10х1.40 м.",
        "check_type": "min_value",
        "metric": "accessible_elevator_width_m",
        "unit": "m",
        "min_value": 1.10,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Lift kabinasi eni {actual}m — kamida {required}m bo'lishi kerak (ShNQ 2.07.02-22 §40)",
        "error_template_ru": "Ширина кабины лифта {actual}м — не менее {required}м (ШНК 2.07.02-22 §40)"
    },
    {
        "id": "UZ-ACC-009",
        "code": "ShNQ 2.07.02-22",
        "clause": "§45",
        "category": "nogironlar_muhiti",
        "severity": "medium",
        "title_uz": "Tutqichlar balandligi (pandus va zinalar)",
        "title_ru": "Высота поручней пандусов и лестниц",
        "description_uz": "Pandus va zinalarda ikki qatorli tutqichlar: yuqorisi 0.90m, pastkisi 0.70m balandlikda.",
        "description_ru": "Высота поручней: верхний 0.90 м, нижний 0.70 м.",
        "check_type": "range",
        "metric": "handrail_height_m",
        "unit": "m",
        "min_value": 0.85,
        "max_value": 0.92,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Tutqich balandligi {actual}m — me'yor: 0.85m dan 0.92m gacha (ShNQ 2.07.02-22 §45)",
        "error_template_ru": "Высота поручня {actual}м — по норме: 0.85-0.92м (ШНК 2.07.02-22 §45)"
    },
    {
        "id": "UZ-ACC-010",
        "code": "ShNQ 2.07.02-22",
        "clause": "§51",
        "category": "nogironlar_muhiti",
        "severity": "high",
        "title_uz": "Nogironlar uchun ajratilgan avtojoy ulushi",
        "title_ru": "Доля парковочных мест для МГН",
        "description_uz": "Umumiy avtoturargohdagi joylarning kamida 10 foizi (kamida 1 ta joy) nogironlar uchun ajratilishi shart.",
        "description_ru": "Не менее 10% мест на стоянке должны выделяться для инвалидов.",
        "check_type": "min_value",
        "metric": "accessible_parking_ratio_percent",
        "unit": "%",
        "min_value": 10.0,
        "applies_to": ["commercial", "public", "residential"],
        "error_template_uz": "Nogironlar avtojoyi ulushi {actual}% — umumiy o'rinlarning kamida {required}% bo'lishi shart (ShNQ 2.07.02-22 §51)",
        "error_template_ru": "Доля мест для инвалидов {actual}% — не менее {required}% (ШНК 2.07.02-22 §51)"
    },

    # ─── 3. TURAR-JOY BINOLARI (ShNQ 2.08.01-19) ───
    {
        "id": "UZ-RES-001",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.1",
        "category": "turar_joy",
        "severity": "critical",
        "title_uz": "Yashash xonalari minimal shift balandligi",
        "title_ru": "Высота жилых помещений от пола до потолка",
        "description_uz": "Turar-joy binolarida yashash xonalari va oshxona shiftining balandligi poldan shiftgacha kamida 2.70 metr.",
        "description_ru": "Высота жилых комнат от пола до потолка должна быть не менее 2.70 м.",
        "check_type": "min_value",
        "metric": "ceiling_height_m",
        "unit": "m",
        "min_value": 2.70,
        "applies_to": ["residential"],
        "error_template_uz": "Shift balandligi {actual}m — kamida {required}m talab etiladi (ShNQ 2.08.01-19 §2.1)",
        "error_template_ru": "Высота потолка {actual}м — по норме не менее {required}м (ШНК 2.08.01-19 §2.1)"
    },
    {
        "id": "UZ-RES-002",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.4",
        "category": "turar_joy",
        "severity": "high",
        "title_uz": "1 xonali kvartirada yashash xonasi minimal maydoni",
        "title_ru": "Площадь жилой комнаты в 1-комнатной квартире",
        "description_uz": "1 xonali kvartiradagi yagona yashash xonasining maydoni kamida 14.0 kv.m bo'lishi shart.",
        "description_ru": "Площадь жилой комнаты в 1-комнатной квартире должна быть не менее 14.0 кв.м.",
        "check_type": "min_value",
        "metric": "one_room_living_area_sqm",
        "unit": "m²",
        "min_value": 14.0,
        "applies_to": ["residential"],
        "error_template_uz": "Yashash xonasi maydoni {actual}m² — kamida {required}m² talab qilinadi (ShNQ 2.08.01-19 §2.4)",
        "error_template_ru": "Площадь комнаты {actual}м² — не менее {required}м² (ШНК 2.08.01-19 §2.4)"
    },
    {
        "id": "UZ-RES-003",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.5",
        "category": "turar_joy",
        "severity": "high",
        "title_uz": "Ko'p xonali kvartirada umumiy xona (zal) maydoni",
        "title_ru": "Площадь общей жилой комнаты (гостиной)",
        "description_uz": "2 va undan ortiq xonali kvartirada umumiy yashash xonasi (mehmonxona) maydoni kamida 16.0 kv.m.",
        "description_ru": "Площадь гостиной должна быть не менее 16.0 кв.м.",
        "check_type": "min_value",
        "metric": "living_room_area_sqm",
        "unit": "m²",
        "min_value": 16.0,
        "applies_to": ["residential"],
        "error_template_uz": "Umumiy xona maydoni {actual}m² — kamida {required}m² talab qilinadi (ShNQ 2.08.01-19 §2.5)",
        "error_template_ru": "Площадь гостиной {actual}м² — не менее {required}м² (ШНК 2.08.01-19 §2.5)"
    },
    {
        "id": "UZ-RES-004",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.6",
        "category": "turar_joy",
        "severity": "high",
        "title_uz": "Yotoqxona minimal maydoni",
        "title_ru": "Минимальная площадь спальни",
        "description_uz": "Ikki kishilik yotoqxona maydoni kamida 10.0 kv.m, bir kishilik kamida 8.0 kv.m bo'lishi lozim.",
        "description_ru": "Площадь спальни должна быть не менее 10.0 кв.м.",
        "check_type": "min_value",
        "metric": "bedroom_area_sqm",
        "unit": "m²",
        "min_value": 10.0,
        "applies_to": ["residential"],
        "error_template_uz": "Yotoqxona maydoni {actual}m² — kamida {required}m² talab qilinadi (ShNQ 2.08.01-19 §2.6)",
        "error_template_ru": "Площадь спальни {actual}м² — не менее {required}м² (ШНК 2.08.01-19 §2.6)"
    },
    {
        "id": "UZ-RES-005",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.8",
        "category": "turar_joy",
        "severity": "high",
        "title_uz": "Alohida oshxona minimal maydoni",
        "title_ru": "Минимальная площадь кухни",
        "description_uz": "Alohida oshxona xonasi maydoni kamida 8.0 kv.m, oshxona-oshxona nishasi kamida 5.0 kv.m.",
        "description_ru": "Площадь кухни должна быть не менее 8.0 кв.м.",
        "check_type": "min_value",
        "metric": "kitchen_area_sqm",
        "unit": "m²",
        "min_value": 8.0,
        "applies_to": ["residential"],
        "error_template_uz": "Oshxona maydoni {actual}m² — kamida {required}m² talab qilinadi (ShNQ 2.08.01-19 §2.8)",
        "error_template_ru": "Площадь кухни {actual}м² — не менее {required}м² (ШНК 2.08.01-19 §2.8)"
    },
    {
        "id": "UZ-RES-006",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.11",
        "category": "turar_joy",
        "severity": "medium",
        "title_uz": "Ichki kvartira yo'lagi (dahliz) kengligi",
        "title_ru": "Ширина внутриквартирного коридора",
        "description_uz": "Kvartira ichidagi yashash xonalariga olib boruvchi yo'laklar kengligi kamida 1.20 metr.",
        "description_ru": "Ширина коридоров в квартире не менее 1.20 м.",
        "check_type": "min_value",
        "metric": "internal_corridor_width_m",
        "unit": "m",
        "min_value": 1.20,
        "applies_to": ["residential"],
        "error_template_uz": "Dahliz/yo'lak kengligi {actual}m — kamida {required}m bo'lishi kerak (ShNQ 2.08.01-19 §2.11)",
        "error_template_ru": "Ширина коридора {actual}м — не менее {required}м (ШНК 2.08.01-19 §2.11)"
    },
    {
        "id": "UZ-RES-007",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.14",
        "category": "turar_joy",
        "severity": "medium",
        "title_uz": "Vanna xonasi minimal kengligi",
        "title_ru": "Минимальная ширина ванной комнаты",
        "description_uz": "Vanna xonasining toza kengligi kamida 1.50 metr bo'lishi shart.",
        "description_ru": "Ширина ванной комнаты должна быть не менее 1.50 м.",
        "check_type": "min_value",
        "metric": "bathroom_width_m",
        "unit": "m",
        "min_value": 1.50,
        "applies_to": ["residential"],
        "error_template_uz": "Vanna xonasi kengligi {actual}m — kamida {required}m talab etiladi (ShNQ 2.08.01-19 §2.14)",
        "error_template_ru": "Ширина ванной {actual}м — не менее {required}м (ШНК 2.08.01-19 §2.14)"
    },
    {
        "id": "UZ-RES-008",
        "code": "ShNQ 2.08.01-19",
        "clause": "§2.15",
        "category": "turar_joy",
        "severity": "medium",
        "title_uz": "Hojatxona xonasi minimal o'lchami",
        "title_ru": "Минимальные размеры туалета",
        "description_uz": "Alohida hojatxona eni kamida 0.85 metr, chuqurligi kamida 1.20 metr.",
        "description_ru": "Ширина туалета не менее 0.85 м, глубина не менее 1.20 м.",
        "check_type": "min_value",
        "metric": "toilet_width_m",
        "unit": "m",
        "min_value": 0.85,
        "applies_to": ["residential"],
        "error_template_uz": "Hojatxona eni {actual}m — kamida {required}m talab qilinadi (ShNQ 2.08.01-19 §2.15)",
        "error_template_ru": "Ширина туалета {actual}м — не менее {required}м (ШНК 2.08.01-19 §2.15)"
    },
    {
        "id": "UZ-RES-009",
        "code": "ShNQ 2.08.01-19",
        "clause": "§3.1",
        "category": "turar_joy",
        "severity": "high",
        "title_uz": "Balkon va lodjiya panjarasi balandligi",
        "title_ru": "Высота ограждения балконов и лоджий",
        "description_uz": "Balkon, lodjiya va ochiq terassalar himoya to'sig'i balandligi kamida 1.20 metr bo'lishi shart.",
        "description_ru": "Высота ограждения балконов и лоджий должна быть не менее 1.20 м.",
        "check_type": "min_value",
        "metric": "balcony_railing_height_m",
        "unit": "m",
        "min_value": 1.20,
        "applies_to": ["residential"],
        "error_template_uz": "Balkon panjarasi balandligi {actual}m — kamida {required}m talab etiladi (ShNQ 2.08.01-19 §3.1)",
        "error_template_ru": "Высота ограждения {actual}м — не менее {required}м (ШНК 2.08.01-19 §3.1)"
    },
    {
        "id": "UZ-RES-010",
        "code": "ShNQ 2.08.01-19",
        "clause": "§4.02",
        "category": "turar_joy",
        "severity": "high",
        "title_uz": "Tabiiy yorug'lik koeffitsiyenti (oyna va pol nisbati)",
        "title_ru": "Отношение площади окон к площади пола",
        "description_uz": "Yashash xonalari va oshxonalarda deraza oynasi maydoni pol maydonining kamida 1:8 qismini (12.5%) tashkil etishi shart.",
        "description_ru": "Отношение площади световых проемов к площади пола не менее 1:8 (12.5%).",
        "check_type": "min_value",
        "metric": "window_to_floor_ratio_percent",
        "unit": "%",
        "min_value": 12.5,
        "applies_to": ["residential"],
        "error_template_uz": "Yorug'lik nisbati {actual}% — me'yor bo'yicha kamida {required}% bo'lishi kerak (ShNQ 2.08.01-19 §4.02)",
        "error_template_ru": "Отношение окон к полу {actual}% — не менее {required}% (ШНК 2.08.01-19 §4.02)"
    },
    {
        "id": "UZ-RES-011",
        "code": "ShNQ 2.08.01-19",
        "clause": "§4.09",
        "category": "turar_joy",
        "severity": "high",
        "title_uz": "Kvartirada quyosh insolyatsiyasi davomiyligi",
        "title_ru": "Продолжительность непрерывной инсоляции",
        "description_uz": "Markaziy zonada (Toshkent, Samarqand) xonalarda to'g'ridan-to'g'ri quyosh tushishi kuniga kamida 2.5 soat bo'lishi shart.",
        "description_ru": "Непрерывная инсоляция жилых комнат должна быть не менее 2.5 часов в день.",
        "check_type": "min_value",
        "metric": "solar_insolation_hours",
        "unit": "soat",
        "min_value": 2.5,
        "applies_to": ["residential"],
        "error_template_uz": "Quyosh insolyatsiyasi {actual} soat — kamida {required} soat to'g'ridan-to'g'ri nurlanish zarur (ShNQ 2.08.01-19 §4.09)",
        "error_template_ru": "Инсоляция {actual} ч — по норме не менее {required} ч (ШНК 2.08.01-19 §4.09)"
    },
    {
        "id": "UZ-RES-012",
        "code": "ShNQ 2.08.01-19",
        "clause": "§5.05",
        "category": "turar_joy",
        "severity": "medium",
        "title_uz": "Zina pog'onasi balandligi (podstupenok)",
        "title_ru": "Высота подступенка лестницы",
        "description_uz": "Turar-joy ichki umumiy zinalarida pog'ona balandligi 0.15 metrdan oshmasligi, eni esa kamida 0.30 metr bo'lishi kerak.",
        "description_ru": "Высота подступенка не более 0.15 м, ширина проступи не менее 0.30 м.",
        "check_type": "max_value",
        "metric": "stair_riser_height_m",
        "unit": "m",
        "max_value": 0.15,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Zina pog'onasi balandligi {actual}m — ruxsat etilgan maksimal me'yor {required}m (ShNQ 2.08.01-19 §5.05)",
        "error_template_ru": "Высота подступенка {actual}м — максимум {required}м (ШНК 2.08.01-19 §5.05)"
    },

    # ─── 4. SEYSMIK XAVFSIZLIK (QMQ 2.01.03-19) ───
    {
        "id": "UZ-SEISMIC-001",
        "code": "QMQ 2.01.03-19",
        "clause": "1-jadval, §1.4",
        "category": "seysmik_xavfsizlik",
        "severity": "critical",
        "title_uz": "Shahar seysmik jadvali va ball normativi",
        "title_ru": "Сейсмичность площадки строительства",
        "description_uz": "Toshkent, Samarqand, Andijon, Namangan, Farg'ona 9 ball; Buxoro, Navoiy 8 ball; Xorazm, Qoraqalpog'iston 7 ball.",
        "description_ru": "Сейсмичность городов Узбекистана (7-9 баллов).",
        "check_type": "categorical",
        "metric": "seismic_zone_ball",
        "unit": "ball",
        "min_value": 7.0,
        "max_value": 9.0,
        "applies_to": ["residential", "commercial", "public", "industrial"],
        "zones": {
            "Toshkent": 9,
            "Samarqand": 9,
            "Andijon": 9,
            "Namangan": 9,
            "Farg'ona": 9,
            "Buxoro": 8,
            "Navoiy": 8,
            "Qarshi": 8,
            "Termiz": 8,
            "Jizzax": 8,
            "Guliston": 8,
            "Urganch": 7,
            "Nukus": 7
        },
        "error_template_uz": "Seysmik ball {actual} — noto'g'ri zona ko'rsatilgan",
        "error_template_ru": "Сейсмический балл {actual} — некорректная зона"
    },
    {
        "id": "UZ-SEISMIC-002",
        "code": "QMQ 2.01.03-19",
        "clause": "2-jadval, §2.3",
        "category": "seysmik_xavfsizlik",
        "severity": "critical",
        "title_uz": "9 ballik zonada monolit karkasli binolar maksimal qavatliligi",
        "title_ru": "Предельная этажность монолитных зданий в 9-балльной зоне",
        "description_uz": "9 ballik seysmik zonada standart monolit temir-beton karkasli binolar 16 qavatdan oshmasligi kerak (16+ maxsus davlat ekspertizasi va dinamik hisob talab qiladi).",
        "description_ru": "В 9-балльной зоне предельная этажность монолитного каркаса — 16 этажей.",
        "check_type": "max_value",
        "metric": "seismic_9_max_floors",
        "unit": "qavat",
        "max_value": 16.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Bino qavatlar soni {actual} — 9 ballik zonada oddiy karkas me'yori {required} qavat (QMQ 2.01.03-19, 2-jadval)",
        "error_template_ru": "Этажность {actual} — в 9-балльной зоне предел {required} этажей (КМК 2.01.03-19)"
    },
    {
        "id": "UZ-SEISMIC-003",
        "code": "QMQ 2.01.03-19",
        "clause": "2-jadval, §2.4",
        "category": "seysmik_xavfsizlik",
        "severity": "critical",
        "title_uz": "9 ballik zonada g'ishtli (nesushiy) binolar maksimal qavatliligi",
        "title_ru": "Предельная этажность кирпичных зданий в 9-балльной зоне",
        "description_uz": "Pishgan g'ishtdan yuk ko'taruvchi devorli binolar 9 ballik zonada 4 qavatdan (12 metr) oshmasligi shart.",
        "description_ru": "Кирпичные несущие здания в 9-балльной зоне не выше 4 этажей.",
        "check_type": "max_value",
        "metric": "masonry_max_floors_9_ball",
        "unit": "qavat",
        "max_value": 4.0,
        "applies_to": ["residential", "public"],
        "error_template_uz": "G'ishtli bino {actual} qavat — 9 ballik zonada ruxsat etilgan maksimal me'yor {required} qavat (QMQ 2.01.03-19)",
        "error_template_ru": "Кирпичное здание {actual} этажей — в 9-балльной зоне максимум {required} этажа (КМК 2.01.03-19)"
    },
    {
        "id": "UZ-SEISMIC-004",
        "code": "QMQ 2.01.03-19",
        "clause": "§2.15",
        "category": "seysmik_xavfsizlik",
        "severity": "critical",
        "title_uz": "Antiseysmik chok minimal kengligi",
        "title_ru": "Ширина антисейсмического шва",
        "description_uz": "Antiseysmik chok kengligi har 10 metr balandlikka kamida 30mm, lekin umumiy kamida 50mm bo'lishi shart.",
        "description_ru": "Ширина антисейсмического шва не менее 50 мм.",
        "check_type": "min_value",
        "metric": "antiseismic_joint_width_mm",
        "unit": "mm",
        "min_value": 50.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Antiseysmik chok kengligi {actual}mm — kamida {required}mm bo'lishi shart (QMQ 2.01.03-19 §2.15)",
        "error_template_ru": "Ширина антисейсмического шва {actual}мм — не менее {required}мм (КМК 2.01.03-19 §2.15)"
    },
    {
        "id": "UZ-SEISMIC-005",
        "code": "QMQ 2.01.03-19",
        "clause": "§3.41",
        "category": "seysmik_xavfsizlik",
        "severity": "critical",
        "title_uz": "Monolit temir-beton ustun minimal kesimi",
        "title_ru": "Минимальное сечение колонн монолитного каркаса",
        "description_uz": "8 va 9 ballik zonalarda to'g'ri burchakli ustunlarning eng kichik tomoni kamida 400mm (0.40m) bo'lishi shart.",
        "description_ru": "Минимальный размер стороны колонны каркаса не менее 400 мм.",
        "check_type": "min_value",
        "metric": "column_min_dimension_mm",
        "unit": "mm",
        "min_value": 400.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Ustun kesimi o'lchami {actual}mm — seysmik zonada kamida {required}mm talab qilinadi (QMQ 2.01.03-19 §3.41)",
        "error_template_ru": "Сечение колонны {actual}мм — требуется не менее {required}мм (КМК 2.01.03-19 §3.41)"
    },
    {
        "id": "UZ-SEISMIC-006",
        "code": "QMQ 2.01.03-19",
        "clause": "§3.48",
        "category": "seysmik_xavfsizlik",
        "severity": "high",
        "title_uz": "Armatura beton himoya qatlami qalinligi",
        "title_ru": "Защитный слой бетона для рабочей арматуры",
        "description_uz": "Yuk ko'taruvchi karkas ustun va to'sinlarida beton himoya qatlami kamida 30mm bo'lishi shart.",
        "description_ru": "Защитный слой бетона не менее 30 мм.",
        "check_type": "min_value",
        "metric": "rebar_concrete_cover_mm",
        "unit": "mm",
        "min_value": 30.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Beton himoya qatlami {actual}mm — kamida {required}mm bo'lishi shart (QMQ 2.01.03-19 §3.48)",
        "error_template_ru": "Защитный слой бетона {actual}мм — не менее {required}мм (КМК 2.01.03-19 §3.48)"
    },
    {
        "id": "UZ-SEISMIC-007",
        "code": "QMQ 2.01.03-19",
        "clause": "§2.08",
        "category": "seysmik_xavfsizlik",
        "severity": "high",
        "title_uz": "Bino rejadagi uzunlik va kenglik nisbati (L/B)",
        "title_ru": "Соотношение длины и ширины здания в плане",
        "description_uz": "9 ballik zonada bino blokining uzunligi uning kengligidan 4 barobardan ortiq bo'lmasligi shart (L/B <= 4.0).",
        "description_ru": "Соотношение длины к ширине здания L/B не должно превышать 4.0.",
        "check_type": "max_value",
        "metric": "building_aspect_ratio_l_b",
        "unit": "nisbat",
        "max_value": 4.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Bino uzunlik/kenglik nisbati {actual} — ruxsat etilgan maksimal me'yor {required} (QMQ 2.01.03-19 §2.08)",
        "error_template_ru": "Соотношение сторон здания {actual} — не более {required} (КМК 2.01.03-19 §2.08)"
    },
    {
        "id": "UZ-SEISMIC-008",
        "code": "QMQ 2.01.03-19",
        "clause": "§3.55",
        "category": "seysmik_xavfsizlik",
        "severity": "critical",
        "title_uz": "Monolit poydevor plitasi (Raft slab) minimal qalinligi",
        "title_ru": "Минимальная толщина фундаментной плиты",
        "description_uz": "Ko'p qavatli (9+ qavat) karkasli binolarda poydevor plitasining qalinligi kamida 600mm (0.60m) bo'lishi shart.",
        "description_ru": "Толщина фундаментной плиты многоэтажных каркасных зданий не менее 600 мм.",
        "check_type": "min_value",
        "metric": "raft_slab_thickness_mm",
        "unit": "mm",
        "min_value": 600.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Poydevor plitasi qalinligi {actual}mm — kamida {required}mm bo'lishi talab etiladi (QMQ 2.01.03-19 §3.55)",
        "error_template_ru": "Толщина фундаментной плиты {actual}мм — не менее {required}мм (КМК 2.01.03-19 §3.55)"
    },
    {
        "id": "UZ-SEISMIC-009",
        "code": "QMQ 2.01.03-19",
        "clause": "§2.12",
        "category": "seysmik_xavfsizlik",
        "severity": "critical",
        "title_uz": "Qo'shni qavatlar og'irlik va qattiqlik farqi",
        "title_ru": "Перепад жесткости и массы смежных этажей",
        "description_uz": "Bino bo'ylab qo'shni qavatlar massasi va gorizontal qattiqligi farqi 20 foizdan oshmasligi kerak (og'ir qavatlar effekti oldini olish).",
        "description_ru": "Перепад массы и жесткости смежных этажей не более 20%.",
        "check_type": "max_value",
        "metric": "inter_story_stiffness_delta_percent",
        "unit": "%",
        "max_value": 20.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Qavatlar qattiqlik farqi {actual}% — ruxsat etilgan maksimal me'yor {required}% (QMQ 2.01.03-19 §2.12)",
        "error_template_ru": "Перепад жесткости {actual}% — максимум {required}% (КМК 2.01.03-19 §2.12)"
    },
    {
        "id": "UZ-SEISMIC-010",
        "code": "QMQ 2.01.03-19",
        "clause": "§3.60",
        "category": "seysmik_xavfsizlik",
        "severity": "high",
        "title_uz": "Monolit antiseysmik belbog' (seysmopoyas) balandligi",
        "title_ru": "Высота антисейсмического пояса",
        "description_uz": "G'ishtli va yig'ma blokli binolarning har bir qavati ustidan o'tadigan uzluksiz antiseysmik belbog' balandligi kamida 150mm.",
        "description_ru": "Высота антисейсмического пояса не менее 150 мм.",
        "check_type": "min_value",
        "metric": "seismic_belt_height_mm",
        "unit": "mm",
        "min_value": 150.0,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Seysmopoyas balandligi {actual}mm — kamida {required}mm talab etiladi (QMQ 2.01.03-19 §3.60)",
        "error_template_ru": "Высота сейсмопояса {actual}мм — не менее {required}мм (КМК 2.01.03-19 §3.60)"
    },

    # ─── 5. SHAHARSOZLIK VA INFRATUZILMA (QMQ 2.07.01-03 / SHNQ 1.03.03-23) ───
    {
        "id": "UZ-URBAN-001",
        "code": "QMQ 2.07.01-03",
        "clause": "§2.14",
        "category": "shaharsozlik",
        "severity": "critical",
        "title_uz": "Magistral ko'cha qizil chizig'idan binogacha masofa",
        "title_ru": "Отступ от красной линии магистральных улиц",
        "description_uz": "Magistral yo'llarning qizil chizig'idan turar-joy va jamoat binolarigacha masofa kamida 6.0 metr bo'lishi shart.",
        "description_ru": "Расстояние от красных линий магистралей до зданий не менее 6.0 м.",
        "check_type": "min_value",
        "metric": "setback_from_major_street_redline_m",
        "unit": "m",
        "min_value": 6.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Qizil chiziqdan masofa {actual}m — me'yor bo'yicha kamida {required}m talab etiladi (QMQ 2.07.01-03 §2.14)",
        "error_template_ru": "Отступ от красной линии {actual}м — требуется не менее {required}м (КМК 2.07.01-03 §2.14)"
    },
    {
        "id": "UZ-URBAN-002",
        "code": "QMQ 2.07.01-03",
        "clause": "§2.15",
        "category": "shaharsozlik",
        "severity": "high",
        "title_uz": "Turar-joy ko'chasi qizil chizig'idan binogacha masofa",
        "title_ru": "Отступ от красной линии жилых улиц",
        "description_uz": "Ichki turar-joy ko'chalari qizil chizig'idan bino fasadiga masofa kamida 3.0 metr bo'lishi shart.",
        "description_ru": "Расстояние от красных линий жилых улиц не менее 3.0 м.",
        "check_type": "min_value",
        "metric": "setback_from_minor_street_redline_m",
        "unit": "m",
        "min_value": 3.0,
        "applies_to": ["residential"],
        "error_template_uz": "Ichki ko'cha qizil chizig'idan masofa {actual}m — kamida {required}m bo'lishi shart (QMQ 2.07.01-03 §2.15)",
        "error_template_ru": "Отступ от жилой улицы {actual}м — не менее {required}м (КМК 2.07.01-03 §2.15)"
    },
    {
        "id": "UZ-URBAN-003",
        "code": "QMQ 2.07.01-03",
        "clause": "§2.18",
        "category": "shaharsozlik",
        "severity": "critical",
        "title_uz": "Turar-joy binolari orasidagi maishiy oraliq masofa",
        "title_ru": "Бытовые разрывы между жилыми зданиями",
        "description_uz": "Baland binolarning uzun tomonlari orasidagi masofa balandroq binoning balandligining kamida 1.5 baravari bo'lishi shart.",
        "description_ru": "Расстояние между длинными сторонами жилых зданий не менее 1.5 высоты здания.",
        "check_type": "min_value",
        "metric": "building_separation_ratio_to_height",
        "unit": "H",
        "min_value": 1.5,
        "applies_to": ["residential"],
        "error_template_uz": "Binolar oralig'i nisbati {actual}H — kamida {required}H (balandlikning 1.5 baravari) bo'lishi shart (QMQ 2.07.01-03 §2.18)",
        "error_template_ru": "Разрыв между зданиями {actual}H — требуется не менее {required}H (КМК 2.07.01-03 §2.18)"
    },
    {
        "id": "UZ-URBAN-004",
        "code": "QMQ 2.07.01-03",
        "clause": "§2.25",
        "category": "shaharsozlik",
        "severity": "high",
        "title_uz": "Turar-joy maydonini ko'kalamzorlashtirish ulushi",
        "title_ru": "Озеленение территории жилой застройки",
        "description_uz": "Kvartal va mikrorayon hududining kamida 25 foizi yashil maydonlar va daraxtzorlar bilan ta'minlangan bo'lishi shart.",
        "description_ru": "Площадь озеленения должна составлять не менее 25% территории.",
        "check_type": "min_value",
        "metric": "greenery_area_percent",
        "unit": "%",
        "min_value": 25.0,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Ko'kalamzorlashtirish ulushi {actual}% — me'yor bo'yicha kamida {required}% bo'lishi shart (QMQ 2.07.01-03 §2.25)",
        "error_template_ru": "Доля озеленения {actual}% — требуется не менее {required}% (КМК 2.07.01-03 §2.25)"
    },
    {
        "id": "UZ-URBAN-005",
        "code": "QMQ 2.07.01-03",
        "clause": "Ilova 9, §1",
        "category": "shaharsozlik",
        "severity": "critical",
        "title_uz": "Kvartiralar soniga nisbatan avtoturargoh o'rinlari",
        "title_ru": "Обеспеченность парковочными местами на квартиру",
        "description_uz": "Yangi qurilayotgan turar-joy binolarida har bir xonadonga kamida 1.0 ta avtoturargoh o'rni bo'lishi shart (1:1 nisbat).",
        "description_ru": "На каждую квартиру должно быть предусмотрено не менее 1.0 парковочного места.",
        "check_type": "min_value",
        "metric": "parking_spots_per_apartment",
        "unit": "joy/xonadon",
        "min_value": 1.0,
        "applies_to": ["residential"],
        "error_template_uz": "Avtojoy ta'minoti {actual} joy/kvartira — me'yor bo'yicha kamida {required} talab etiladi (QMQ 2.07.01-03 Ilova 9)",
        "error_template_ru": "Парковочных мест {actual} на квартиру — требуется не менее {required} (КМК 2.07.01-03 Приложение 9)"
    },
    {
        "id": "UZ-URBAN-006",
        "code": "QMQ 2.07.01-03",
        "clause": "§2.30",
        "category": "shaharsozlik",
        "severity": "medium",
        "title_uz": "Bolalar o'yingohigacha masofa",
        "title_ru": "Расстояние до детских площадок от окон",
        "description_uz": "Bolalar o'yin maydonchalari turar-joy derazalaridan kamida 12 metr masofada joylashtirilishi shart.",
        "description_ru": "Расстояние от окон жилых домов до детских площадок не менее 12 м.",
        "check_type": "min_value",
        "metric": "playground_distance_from_windows_m",
        "unit": "m",
        "min_value": 12.0,
        "applies_to": ["residential"],
        "error_template_uz": "Bolalar maydonchasi masofasi {actual}m — kamida {required}m bo'lishi lozim (QMQ 2.07.01-03 §2.30)",
        "error_template_ru": "Расстояние до детской площадки {actual}м — не менее {required}м (КМК 2.07.01-03 §2.30)"
    },
    {
        "id": "UZ-URBAN-007",
        "code": "QMQ 2.07.01-03",
        "clause": "§2.32",
        "category": "shaharsozlik",
        "severity": "high",
        "title_uz": "Maishiy chiqindi yig'ish maydonchasi masofasi",
        "title_ru": "Расстояние до площадок мусоросборников",
        "description_uz": "Chiqindi konteynerlari turar-joy derazalari va bolalar maydonchalaridan kamida 20m, ko'pi bilan 100m masofada bo'lishi shart.",
        "description_ru": "Расстояние до мусоросборников от 20 до 100 м.",
        "check_type": "range",
        "metric": "waste_collection_distance_m",
        "unit": "m",
        "min_value": 20.0,
        "max_value": 100.0,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Chiqindi maydonchasi masofasi {actual}m — me'yor: 20m dan 100m gacha (QMQ 2.07.01-03 §2.32)",
        "error_template_ru": "Расстояние до мусоросборника {actual}м — норма 20-100м (КМК 2.07.01-03 §2.32)"
    },
    {
        "id": "UZ-URBAN-008",
        "code": "QMQ 2.07.01-03",
        "clause": "§2.35",
        "category": "shaharsozlik",
        "severity": "high",
        "title_uz": "Ochiq avtoturargohdan turar-joy fasadigacha masofa",
        "title_ru": "Расстояние от открытых автостоянок до фасада жилого дома",
        "description_uz": "10 tagacha mashina sig'adigan ochiq avtoturargoh derazalardan kamida 10m masofada bo'lishi shart.",
        "description_ru": "Расстояние от автостоянки до 10 машин до окон дома не менее 10 м.",
        "check_type": "min_value",
        "metric": "open_parking_distance_from_facade_m",
        "unit": "m",
        "min_value": 10.0,
        "applies_to": ["residential"],
        "error_template_uz": "Avtoturargohdan fasadgacha masofa {actual}m — kamida {required}m bo'lishi shart (QMQ 2.07.01-03 §2.35)",
        "error_template_ru": "Расстояние до стоянки {actual}м — не менее {required}м (КМК 2.07.01-03 §2.35)"
    },
    {
        "id": "UZ-URBAN-009",
        "code": "SHNQ 1.03.03-23",
        "clause": "§3.2",
        "category": "shaharsozlik",
        "severity": "critical",
        "title_uz": "Turar-joy hududining qurilish zichligi koeffitsiyenti (K2)",
        "title_ru": "Коэффициент плотности застройки (К2)",
        "description_uz": "Ko'p qavatli turar-joy kvartalida qurilish zichligi koeffitsiyenti (K2) 1.6 dan oshmasligi shart.",
        "description_ru": "Коэффициент плотности застройки жилого квартала не более 1.6.",
        "check_type": "max_value",
        "metric": "building_density_coefficient_k2",
        "unit": "koeff",
        "max_value": 1.6,
        "applies_to": ["residential"],
        "error_template_uz": "Qurilish zichligi K2={actual} — ruxsat etilgan maksimal me'yor {required} (SHNQ 1.03.03-23 §3.2)",
        "error_template_ru": "Плотность застройки К2={actual} — максимум {required} (ШНК 1.03.03-23 §3.2)"
    },
    {
        "id": "UZ-URBAN-010",
        "code": "QMQ 2.07.01-03",
        "clause": "Ilova 14",
        "category": "shaharsozlik",
        "severity": "high",
        "title_uz": "Yer osti gaz quvuridan bino poydevorigacha xavfsizlik masofasi",
        "title_ru": "Расстояние от газопровода низкого давления до фундамента",
        "description_uz": "Past bosimli gaz quvuridan bino poydevorigacha bo'lgan gorizontal toza masofa kamida 2.0 metr.",
        "description_ru": "Расстояние от газопровода низкого давления до фундамента не менее 2.0 м.",
        "check_type": "min_value",
        "metric": "gas_pipeline_distance_to_foundation_m",
        "unit": "m",
        "min_value": 2.0,
        "applies_to": ["residential", "commercial", "public"],
        "error_template_uz": "Gaz quvurigacha masofa {actual}m — kamida {required}m bo'lishi shart (QMQ 2.07.01-03 Ilova 14)",
        "error_template_ru": "Расстояние до газопровода {actual}м — не менее {required}м (КМК 2.07.01-03 Приложение 14)"
    },

    # ─── 6. QO'SHIMCHA MUHANDISLIK VA ENERGIYA TEJAMKORLIK ME'YORLARI (QMQ 2.01.04-18 / SHNQ 2.04.01-98) ───
    {
        "id": "UZ-ENG-001",
        "code": "QMQ 2.01.04-18",
        "clause": "§4.2",
        "category": "energiya_samaradorligi",
        "severity": "high",
        "title_uz": "Tashqi devorlar issiqlik o'tkazuvchanligiga qarshiligi (R_req)",
        "title_ru": "Сопротивление теплопередаче наружных стен",
        "description_uz": "Toshkent iqlimi uchun turar-joy tashqi devorlarining issiqlik himoyasi kamida 2.2 m²·°C/Vt bo'lishi shart.",
        "description_ru": "Требуемое сопротивление теплопередаче стен не менее 2.2 м²·°С/Вт.",
        "check_type": "min_value",
        "metric": "wall_thermal_resistance_r",
        "unit": "m²·°C/Vt",
        "min_value": 2.2,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Devor issiqlik qarshiligi R={actual} — me'yor bo'yicha kamida {required} m²·°C/Vt talab etiladi (QMQ 2.01.04-18)",
        "error_template_ru": "Теплосопротивление стены R={actual} — требуется не менее {required} (КМК 2.01.04-18)"
    },
    {
        "id": "UZ-ENG-002",
        "code": "SHNQ 2.04.01-98",
        "clause": "§3.14",
        "category": "muhandislik_tarmoqlari",
        "severity": "medium",
        "title_uz": "Xonadon ichki sovuq suv bosimi",
        "title_ru": "Свободный напор холодной воды у санитарных приборов",
        "description_uz": "Eng yuqori qavatdagi suv asboblarida erkin bosim kamida 0.2 MPa (20m suv ustuni) bo'lishi shart.",
        "description_ru": "Свободный напор у санприборов на верхнем этаже не менее 0.2 МПа.",
        "check_type": "min_value",
        "metric": "water_pressure_mpa",
        "unit": "MPa",
        "min_value": 0.2,
        "applies_to": ["residential", "public"],
        "error_template_uz": "Suv bosimi {actual} MPa — me'yor bo'yicha kamida {required} MPa talab etiladi (SHNQ 2.04.01-98)",
        "error_template_ru": "Напор воды {actual} МПа — не менее {required} МПа (ШНК 2.04.01-98)"
    }
]

def main():
    rules_file = Path(__file__).parent / "qmq_rules_v1.json"
    
    meta = {
        "version": "2.0.0",
        "created": "2026-09-30",
        "jurisdiction": "UZ",
        "description": "Me'morAI QMQ/ShNQ kengaytirilgan qoidalar bazasi (52 ta me'yor) — O'zbekiston Respublikasi rasmiy shaharsozlik qonunchiligi asosida",
        "sources": [
            "ShNQ 2.01.02-04 (mc.uz) — Binolar va inshootlarning yong'in xavfsizligi",
            "ShNQ 2.07.02-22 (mc.uz) — Nogironligi bo'lgan shaxslar va keksalar uchun loyihalashtirish",
            "ShNQ 2.08.01-19 (mc.uz) — Turar joy binolari",
            "QMQ 2.01.03-19 (mc.uz) — Seysmik hududlarda qurilish",
            "QMQ 2.07.01-03 (mc.uz) — Shahar va qishloq aholi punktlarini rejalashtirish va qurish",
            "SHNQ 1.03.03-23 (mc.uz) — Qurilish obyektlarini loyihalashtirish",
            "QMQ 2.01.04-18 (mc.uz) — Qurilish issiqlik texnikasi"
        ],
        "official_portal": "https://mc.uz",
        "legal_portal": "https://lex.uz",
        "total_rules": len(RULES)
    }
    
    payload = {
        "_meta": meta,
        "rules": RULES
    }
    
    with open(rules_file, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        
    print(f"✅ Muvaffaqiyatli saqlandi! Jami qoidalar soni: {len(RULES)}")

if __name__ == "__main__":
    main()
